runtime: custom
env: flex

network:
  instance_tag: easycov-app-engine
  name: ercov-network
  subnetwork_name: ercov-subnet-1

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
